name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python, Pipenv, dependency packages
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: 3.11
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pipenv run ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          pipenv run ruff --format=github --target-version=py37 .
      - name: Test with pytest
        run: |
          pipenv run pip freeze
          pipenv run python -c "import yaml; print(yaml.__version__)"
          pipenv run python -c "from yaml import load"
          pipenv run pytest
